version: '3'
services:
    m3e-server:
        build: .
        container_name: m3e-server
        restart: always
        ports:
            - "6800:6800"
        volumes:
            - ./hf_cache:/root/.cache
#        environment:
#            - TRANSFORMERS_OFFLINE=1
        command: moka-ai/m3e-base moka-ai/m3e-small
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [ gpu ]