version: '3'
services:
    m3e-server:
        image: theone1006/m3e-server:latest
        container_name: m3e-server
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./hf_cache:/root/.cache
#        environment:
#            - TRANSFORMERS_OFFLINE=1
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [ gpu ]